import {useState,type FormEvent} from'react';import{ArrowUpRight,ChevronDown,Mail,MapPin,Menu,MessageCircle,X}from'lucide-react';import'./App.css';
const PHONE='50760634535',WA=`https://wa.me/${PHONE}`,EMAIL='jsgsoftwares@gmail.com';
const services=[['Integraciones empresariales','Conectamos bancos, Zoho, Odoo y plataformas internas para que la información fluya sin doble registro.','APIs · OAuth2 · Webhooks'],['Automatización de procesos','Convertimos tareas repetitivas en flujos confiables con n8n, alertas, reintentos y trazabilidad.','n8n · Cron · Monitoreo'],['Software a la medida','Desarrollamos portales, paneles y herramientas ajustadas a la forma real de trabajar de tu equipo.','Laravel · React · AWS'],['Odoo y facturación','Implementamos y personalizamos Odoo, incluyendo integraciones y facturación electrónica para Panamá.','Odoo · ERP · Panamá']];
const projects=[['Integración bancaria','Banco General conectado con Zoho Creator','Sincronización de movimientos, renovación de credenciales, control de duplicados y bitácora para auditoría.','Menos registro manual y una operación verificable.'],['Pagos digitales','Cobros con Yappy para una plataforma digital','Botón de pago, confirmación por webhook y panel para consultar el estado de cada transacción.','Confirmación automática desde el primer día.'],['Operación comercial','Odoo adaptado a un flujo fiscal local','Configuración de módulos, reportes propios e integración de los datos existentes del negocio.','Un solo sistema para vender, facturar y dar seguimiento.']];
const faqs=[['¿Con qué tipo de empresas trabajan?','Principalmente con pymes y equipos operativos que ya usan varias herramientas y necesitan conectarlas o reemplazar procesos manuales.'],['¿Pueden trabajar sobre un sistema existente?','Sí. Revisamos la arquitectura y el estado del código; luego proponemos una integración o mejora gradual.'],['¿Cómo se define el costo?','Después de una conversación inicial preparamos un alcance con entregables, supuestos, tiempo y precio.'],['¿Ofrecen soporte después de entregar?','Sí. Incluimos estabilización y documentación, y podemos acordar soporte continuo cuando haga falta.']];
function Logo(){return <a className="logo" href="#inicio" aria-label="JSG Softwares"><span>&lt;/</span>JSG<span>&gt;</span><small>softwares</small></a>}
function Form(){const[n,setN]=useState(''),[m,setM]=useState('');function send(e:FormEvent){e.preventDefault();open(`${WA}?text=${encodeURIComponent(`Hola JSG, soy ${n}. ${m}`)}`,'_blank')}return <form className="form" onSubmit={send}><label>Tu nombre<input value={n} onChange={e=>setN(e.target.value)} placeholder="¿Cómo te llamas?" required/></label><label>Cuéntanos brevemente qué necesitas<textarea value={m} onChange={e=>setM(e.target.value)} placeholder="Por ejemplo: necesito conectar las ventas de Odoo con..." rows={4} required/></label><button className="button" type="submit">Continuar por WhatsApp <ArrowUpRight size={17}/></button></form>}
export default function App(){const[menu,setMenu]=useState(false),[faq,setFaq]=useState<number|null>(null);return <div className="page"><header><div className="container head"><Logo/><nav className={menu?'open':''}><a href="#servicios">Servicios</a><a href="#trabajo">Trabajo</a><a href="#proceso">Proceso</a><a href="#contacto">Contacto</a></nav><a className="talk" href={WA}>Hablemos <ArrowUpRight size={16}/></a><button className="menub" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header><main>
<section id="inicio" className="hero"><div className="container heroGrid"><div><p className="kicker dot">Software e integraciones desde Panamá</p><h1>Hacemos que tus sistemas <em>trabajen juntos.</em></h1><p className="lead">Diseñamos software, automatizaciones e integraciones para empresas que quieren operar con menos pasos manuales y mejor información.</p><div className="actions"><a className="button" href="#contacto">Cuéntanos tu proyecto <ArrowUpRight size={18}/></a><a href="#trabajo">Ver cómo trabajamos ↓</a></div></div><aside><p>En qué somos buenos</p>{[['Conectar','APIs, bancos, Odoo y Zoho'],['Automatizar','procesos repetitivos y validaciones'],['Construir','software que encaja con tu operación']].map(x=><div key={x[0]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}<small>Analiza · Integra · Transforma</small></aside></div></section>
<section className="tech"><div className="container"><span>Tecnologías con las que trabajamos</span>{['Laravel','Odoo','Zoho','n8n','AWS','React'].map(x=><b key={x}>{x}</b>)}</div></section>
<section id="servicios" className="section"><div className="container"><Heading k="Servicios" h="Soluciones concretas para operaciones reales." p="No vendemos transformación digital en abstracto. Entendemos el problema, definimos el alcance y construimos lo necesario."/><div className="services">{services.map((s,i)=><article key={s[0]}><span>0{i+1}</span><div><h3>{s[0]}</h3><p>{s[1]}</p><small>{s[2]}</small></div><ArrowUpRight/></article>)}</div></div></section>
<section id="trabajo" className="section light"><div className="container"><Heading k="Trabajo reciente" h="Menos promesas. Más contexto." p="Una muestra del tipo de problemas técnicos y operativos que resolvemos."/><div className="projects">{projects.map((p,i)=><article key={p[1]}><span>0{i+1}</span><small>{p[0]}</small><h3>{p[1]}</h3><p>{p[2]}</p><strong>{p[3]}</strong></article>)}</div></div></section>
<section id="proceso" className="section"><div className="container process"><Heading k="Nuestra forma de trabajar" h="Primero entendemos. Después escribimos código."/ ><ol>{[['Conversación técnica','Nos cuentas cómo funciona hoy, qué falla y qué resultado esperas.'],['Alcance claro','Definimos entregables, riesgos, responsabilidades, tiempo y precio.'],['Construcción visible','Avanzamos por etapas y te mostramos resultados durante el proyecto.'],['Entrega y continuidad','Probamos, documentamos y dejamos un camino claro para soporte.']].map((x,i)=><li key={x[0]}><span>0{i+1}</span><div><strong>{x[0]}</strong><p>{x[1]}</p></div></li>)}</ol></div></section>
<section className="section faq"><div className="container faqGrid"><Heading k="Preguntas habituales" h="Antes de empezar."/><div>{faqs.map((f,i)=><div className="faqItem" key={f[0]}><button onClick={()=>setFaq(faq===i?null:i)}>{f[0]}<ChevronDown className={faq===i?'rotate':''}/></button>{faq===i&&<p>{f[1]}</p>}</div>)}</div></div></section>
<section id="contacto" className="contact"><div className="container contactGrid"><div><p className="kicker">Hablemos</p><h2>¿Hay un proceso que te está quitando tiempo?</h2><p>Cuéntanos cómo funciona hoy. Te diremos con honestidad si podemos ayudarte y cuál sería el siguiente paso.</p><div className="details"><a href={`mailto:${EMAIL}`}><Mail/>{EMAIL}</a><a href={WA}><MessageCircle/>+507 6063-4535</a><span><MapPin/>Ciudad de Panamá</span></div></div><Form/></div></section></main><footer><div className="container foot"><Logo/><p>© {new Date().getFullYear()} JSG Softwares</p><p>Analiza · Integra · Transforma</p></div></footer></div>}
function Heading({k,h,p}:{k:string,h:string,p?:string}){return <div className="heading"><p className="kicker">{k}</p><h2>{h}</h2>{p&&<p>{p}</p>}</div>}
